import Head from 'next/head';
import { useEffect } from 'react';

export default function Home() {
  const handleLogin = () => {
    if (Kakao.isInitialized()) {
      Kakao.Auth.authorize({
        redirectUri: process.env.NEXT_PUBLIC_REDIRECT_URI,
      });
    }
  };

  useEffect(() => {
    Kakao.init(process.env.NEXT_PUBLIC_KAKAO_KEY);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>포텐파이낸스</h1>
        <button onClick={handleLogin}>카카오 로그인</button>
      </main>
      <footer></footer>
    </>
  );
}
